using Core.Objects.Entities.Security;

namespace Core.Data
{
    public partial class CoreDataContext
    {
        public Privilege[] GetAllPrivileges() => Privileges;

        static Privilege[] Privileges = new[]
        {
            new Privilege { Id = "app_admin",                   Type = "App",               Operation = "Admin",            Description = "Marks users in this role as App Admins.",    PortalAdminsOnly = false },
            new Privilege { Id = "app_create",                  Type = "App",               Operation = "Create",           Description = "Allows users to Create Apps.",               PortalAdminsOnly = false },
            new Privilege { Id = "app_delete",                  Type = "App",               Operation = "Delete",           Description = "Allows users to Delete Apps.",               PortalAdminsOnly = false },
            new Privilege { Id = "app_read",                    Type = "App",               Operation = "Read",             Description = "Allows users to Read Apps.",                 PortalAdminsOnly = false },
            new Privilege { Id = "app_update",                  Type = "App",               Operation = "Update",           Description = "Allows users to Update Apps.",               PortalAdminsOnly = false },
            new Privilege { Id = "appculture_create",           Type = "AppCulture",        Operation = "Create",           Description = "Allows users to Create AppCultures.",        PortalAdminsOnly = false },
            new Privilege { Id = "appculture_delete",           Type = "AppCulture",        Operation = "Delete",           Description = "Allows users to Delete AppCultures.",        PortalAdminsOnly = false },
            new Privilege { Id = "appculture_read",             Type = "AppCulture",        Operation = "Read",             Description = "Allows users to Read AppCultures.",          PortalAdminsOnly = false },
            new Privilege { Id = "appculture_update",           Type = "AppCulture",        Operation = "Update",           Description = "Allows users to Update AppCultures.",        PortalAdminsOnly = false },
            new Privilege { Id = "backgroundjob_create",        Type = "BackgroundJob",     Operation = "Create",           Description = "Allows users to Create BackgroundJobs.",     PortalAdminsOnly = false },
            new Privilege { Id = "backgroundjob_delete",        Type = "BackgroundJob",     Operation = "Delete",           Description = "Allows users to Delete BackgroundJobs.",     PortalAdminsOnly = false },
            new Privilege { Id = "backgroundjob_read",          Type = "BackgroundJob",     Operation = "Read",             Description = "Allows users to Read BackgroundJobs.",       PortalAdminsOnly = false },
            new Privilege { Id = "backgroundjob_update",        Type = "BackgroundJob",     Operation = "Update",           Description = "Allows users to Update BackgroundJobs.",     PortalAdminsOnly = false },
            new Privilege { Id = "businessprocess_create",      Type = "BusinessProcess",   Operation = "Create",           Description = "Allows users to Create BusinessProcesses.",  PortalAdminsOnly = false },
            new Privilege { Id = "businessprocess_delete",      Type = "BusinessProcess",   Operation = "Delete",           Description = "Allows users to Delete BusinessProcesses.",  PortalAdminsOnly = false },
            new Privilege { Id = "businessprocess_read",        Type = "BusinessProcess",   Operation = "Read",             Description = "Allows users to Read BusinessProcesses.",    PortalAdminsOnly = false },
            new Privilege { Id = "businessprocess_update",      Type = "BusinessProcess",   Operation = "Update",           Description = "Allows users to Update BusinessProcesses.",  PortalAdminsOnly = false },
            new Privilege { Id = "calendar_create",             Type = "Calendar",          Operation = "Create",           Description = "Allows users to Create Calendars.",          PortalAdminsOnly = false },
            new Privilege { Id = "calendar_delete",             Type = "Calendar",          Operation = "Delete",           Description = "Allows users to Delete Calendars.",          PortalAdminsOnly = false },
            new Privilege { Id = "calendar_read",               Type = "Calendar",          Operation = "Read",             Description = "Allows users to Read Calendars.",            PortalAdminsOnly = false },
            new Privilege { Id = "calendar_update",             Type = "Calendar",          Operation = "Update",           Description = "Allows users to Update Calendars.",          PortalAdminsOnly = false },
            new Privilege { Id = "calendarevent_create",        Type = "CalendarEvent",     Operation = "Create",           Description = "Allows users to Create CalendarEvents.",     PortalAdminsOnly = false },
            new Privilege { Id = "calendarevent_delete",        Type = "CalendarEvent",     Operation = "Delete",           Description = "Allows users to Delete CalendarEvents.",     PortalAdminsOnly = false },
            new Privilege { Id = "calendarevent_read",          Type = "CalendarEvent",     Operation = "Read",             Description = "Allows users to Read CalendarEvents.",       PortalAdminsOnly = false },
            new Privilege { Id = "calendarevent_update",        Type = "CalendarEvent",     Operation = "Update",           Description = "Allows users to Update CalendarEvents.",     PortalAdminsOnly = false },
            new Privilege { Id = "commonobject_create",         Type = "CommonObject",      Operation = "Create",           Description = "Allows users to Create CommonObjects.",      PortalAdminsOnly = false },
            new Privilege { Id = "commonobject_delete",         Type = "CommonObject",      Operation = "Delete",           Description = "Allows users to Delete CommonObjects.",      PortalAdminsOnly = false },
            new Privilege { Id = "commonobject_read",           Type = "CommonObject",      Operation = "Read",             Description = "Allows users to Read CommonObjects.",        PortalAdminsOnly = false },
            new Privilege { Id = "commonobject_update",         Type = "CommonObject",      Operation = "Update",           Description = "Allows users to Update CommonObjects.",      PortalAdminsOnly = false },
            new Privilege { Id = "component_create",            Type = "Component",         Operation = "Create",           Description = "Allows users to Create Components.",         PortalAdminsOnly = false },
            new Privilege { Id = "component_delete",            Type = "Component",         Operation = "Delete",           Description = "Allows users to Delete Components.",         PortalAdminsOnly = false },
            new Privilege { Id = "component_read",              Type = "Component",         Operation = "Read",             Description = "Allows users to Read Components.",           PortalAdminsOnly = false },
            new Privilege { Id = "component_render",            Type = "Component",         Operation = "Render",           Description = "Allows users to call Render on Components.", PortalAdminsOnly = false },
            new Privilege { Id = "component_update",            Type = "Component",         Operation = "Update",           Description = "Allows users to Update Components.",         PortalAdminsOnly = false },
            new Privilege { Id = "content_create",              Type = "Content",           Operation = "Create",           Description = "Allows users to Create Contents.",           PortalAdminsOnly = false },
            new Privilege { Id = "content_delete",              Type = "Content",           Operation = "Delete",           Description = "Allows users to Delete Contents.",           PortalAdminsOnly = false },
            new Privilege { Id = "content_read",                Type = "Content",           Operation = "Read",             Description = "Allows users to Read Contents.",             PortalAdminsOnly = false },
            new Privilege { Id = "content_update",              Type = "Content",           Operation = "Update",           Description = "Allows users to Update Contents.",           PortalAdminsOnly = false },
            new Privilege { Id = "culture_create",              Type = "Culture",           Operation = "Create",           Description = "Allows users to Create Cultures.",           PortalAdminsOnly = false },
            new Privilege { Id = "culture_delete",              Type = "Culture",           Operation = "Delete",           Description = "Allows users to Delete Cultures.",           PortalAdminsOnly = false },
            new Privilege { Id = "culture_read",                Type = "Culture",           Operation = "Read",             Description = "Allows users to Read Cultures.",             PortalAdminsOnly = false },
            new Privilege { Id = "culture_update",              Type = "Culture",           Operation = "Update",           Description = "Allows users to Update Cultures.",           PortalAdminsOnly = false },
            new Privilege { Id = "emailsendfailure_create",     Type = "EmailSendFailure",  Operation = "Create",           Description = "Allows users to Create EmailSendFailures.",  PortalAdminsOnly = false },
            new Privilege { Id = "emailsendfailure_delete",     Type = "EmailSendFailure",  Operation = "Delete",           Description = "Allows users to Delete EmailSendFailures.",  PortalAdminsOnly = false },
            new Privilege { Id = "emailsendfailure_read",       Type = "EmailSendFailure",  Operation = "Read",             Description = "Allows users to Read EmailSendFailures.",    PortalAdminsOnly = false },
            new Privilege { Id = "emailsendfailure_update",     Type = "EmailSendFailure",  Operation = "Update",           Description = "Allows users to Update EmailSendFailures.",  PortalAdminsOnly = false },
            new Privilege { Id = "file_create",                 Type = "File",              Operation = "Create",           Description = "Allows users to Create Files.",              PortalAdminsOnly = false },
            new Privilege { Id = "file_delete",                 Type = "File",              Operation = "Delete",           Description = "Allows users to Delete Files.",              PortalAdminsOnly = false },
            new Privilege { Id = "file_read",                   Type = "File",              Operation = "Read",             Description = "Allows users to Read Files.",                PortalAdminsOnly = false },
            new Privilege { Id = "file_update",                 Type = "File",              Operation = "Update",           Description = "Allows users to Update Files.",              PortalAdminsOnly = false },
            new Privilege { Id = "file_updatecontents",         Type = "File",              Operation = "UpdateContents",   Description = "Allows users to call UpdateContents on Files.", PortalAdminsOnly = false },
            new Privilege { Id = "filecontent_create",          Type = "FileContent",       Operation = "Create",           Description = "Allows users to Create FileContents.",       PortalAdminsOnly = false },
            new Privilege { Id = "filecontent_delete",          Type = "FileContent",       Operation = "Delete",           Description = "Allows users to Delete FileContents.",       PortalAdminsOnly = false },
            new Privilege { Id = "filecontent_read",            Type = "FileContent",       Operation = "Read",             Description = "Allows users to Read FileContents.",         PortalAdminsOnly = false },
            new Privilege { Id = "filecontent_update",          Type = "FileContent",       Operation = "Update",           Description = "Allows users to Update FileContents.",       PortalAdminsOnly = false },
            new Privilege { Id = "flowdefinition_create",       Type = "FlowDefinition",    Operation = "Create",           Description = "Allows users to Create FlowDefinitions.",    PortalAdminsOnly = false },
            new Privilege { Id = "flowdefinition_delete",       Type = "FlowDefinition",    Operation = "Delete",           Description = "Allows users to Delete FlowDefinitions.",    PortalAdminsOnly = false },
            new Privilege { Id = "flowdefinition_execute",      Type = "FlowDefinition",    Operation = "Execute",          Description = "Allows users to call Execute on FlowDefinitions.", PortalAdminsOnly = false },
            new Privilege { Id = "flowdefinition_read",         Type = "FlowDefinition",    Operation = "Read",             Description = "Allows users to Read FlowDefinitions.",      PortalAdminsOnly = false },
            new Privilege { Id = "flowdefinition_update",       Type = "FlowDefinition",    Operation = "Update",           Description = "Allows users to Update FlowDefinitions.",    PortalAdminsOnly = false },
            new Privilege { Id = "flowinstancedata_create",     Type = "FlowInstanceData",  Operation = "Create",           Description = "Allows users to Create FlowInstanceDatas.",  PortalAdminsOnly = false },
            new Privilege { Id = "flowinstancedata_delete",     Type = "FlowInstanceData",  Operation = "Delete",           Description = "Allows users to Delete FlowInstanceDatas.",  PortalAdminsOnly = false },
            new Privilege { Id = "flowinstancedata_read",       Type = "FlowInstanceData",  Operation = "Read",             Description = "Allows users to Read FlowInstanceDatas.",    PortalAdminsOnly = false },
            new Privilege { Id = "flowinstancedata_update",     Type = "FlowInstanceData",  Operation = "Update",           Description = "Allows users to Update FlowInstanceDatas.",  PortalAdminsOnly = false },
            new Privilege { Id = "folder_create",               Type = "Folder",            Operation = "Create",           Description = "Allows users to Create Folders.",            PortalAdminsOnly = false },
            new Privilege { Id = "folder_delete",               Type = "Folder",            Operation = "Delete",           Description = "Allows users to Delete Folders.",            PortalAdminsOnly = false },
            new Privilege { Id = "folder_read",                 Type = "Folder",            Operation = "Read",             Description = "Allows users to Read Folders.",              PortalAdminsOnly = false },
            new Privilege { Id = "folder_update",               Type = "Folder",            Operation = "Update",           Description = "Allows users to Update Folders.",            PortalAdminsOnly = false },
            new Privilege { Id = "folder_updatefiles",          Type = "Folder",            Operation = "UpdateFiles",      Description = "Allows users to manage Files for a folder.", PortalAdminsOnly = false },
            new Privilege { Id = "folder_updateroles",          Type = "Folder",            Operation = "UpdateRoles",      Description = "Allows users to manage Roles for a folder.", PortalAdminsOnly = false },
            new Privilege { Id = "folder_updatesubfolders",     Type = "Folder",            Operation = "UpdateSubFolders", Description = "Allows users to manage Sub folders for a folder.", PortalAdminsOnly = false },
            new Privilege { Id = "folderrole_create",           Type = "FolderRole",        Operation = "Create",           Description = "Allows users to Create FolderRoles.",        PortalAdminsOnly = false },
            new Privilege { Id = "folderrole_delete",           Type = "FolderRole",        Operation = "Delete",           Description = "Allows users to Delete FolderRoles.",        PortalAdminsOnly = false },
            new Privilege { Id = "folderrole_read",             Type = "FolderRole",        Operation = "Read",             Description = "Allows users to Read FolderRoles.",          PortalAdminsOnly = false },
            new Privilege { Id = "folderrole_update",           Type = "FolderRole",        Operation = "Update",           Description = "Allows users to Update FolderRoles.",        PortalAdminsOnly = false },
            new Privilege { Id = "layout_create",               Type = "Layout",            Operation = "Create",           Description = "Allows users to Create Layouts.",            PortalAdminsOnly = false },
            new Privilege { Id = "layout_delete",               Type = "Layout",            Operation = "Delete",           Description = "Allows users to Delete Layouts.",            PortalAdminsOnly = false },
            new Privilege { Id = "layout_read",                 Type = "Layout",            Operation = "Read",             Description = "Allows users to Read Layouts.",              PortalAdminsOnly = false },
            new Privilege { Id = "layout_update",               Type = "Layout",            Operation = "Update",           Description = "Allows users to Update Layouts.",            PortalAdminsOnly = false },
            new Privilege { Id = "logdataitem_create",          Type = "LogDataItem",       Operation = "Create",           Description = "Allows users to Create LogDataItems.",       PortalAdminsOnly = false },
            new Privilege { Id = "logdataitem_delete",          Type = "LogDataItem",       Operation = "Delete",           Description = "Allows users to Delete LogDataItems.",       PortalAdminsOnly = false },
            new Privilege { Id = "logdataitem_read",            Type = "LogDataItem",       Operation = "Read",             Description = "Allows users to Read LogDataItems.",         PortalAdminsOnly = false },
            new Privilege { Id = "logdataitem_update",          Type = "LogDataItem",       Operation = "Update",           Description = "Allows users to Update LogDataItems.",       PortalAdminsOnly = false },
            new Privilege { Id = "logentry_create",             Type = "LogEntry",          Operation = "Create",           Description = "Allows users to Create LogEntrys.",          PortalAdminsOnly = false },
            new Privilege { Id = "logentry_delete",             Type = "LogEntry",          Operation = "Delete",           Description = "Allows users to Delete LogEntrys.",          PortalAdminsOnly = false },
            new Privilege { Id = "logentry_read",               Type = "LogEntry",          Operation = "Read",             Description = "Allows users to Read LogEntrys.",            PortalAdminsOnly = false },
            new Privilege { Id = "logentry_update",             Type = "LogEntry",          Operation = "Update",           Description = "Allows users to Update LogEntrys.",          PortalAdminsOnly = false },
            new Privilege { Id = "mailserver_create",           Type = "MailServer",        Operation = "Create",           Description = "Allows users to Create MailServers.",        PortalAdminsOnly = false },
            new Privilege { Id = "mailserver_delete",           Type = "MailServer",        Operation = "Delete",           Description = "Allows users to Delete MailServers.",        PortalAdminsOnly = false },
            new Privilege { Id = "mailserver_read",             Type = "MailServer",        Operation = "Read",             Description = "Allows users to Read MailServers.",          PortalAdminsOnly = false },
            new Privilege { Id = "mailserver_update",           Type = "MailServer",        Operation = "Update",           Description = "Allows users to Update MailServers.",        PortalAdminsOnly = false },
            new Privilege { Id = "package_create",              Type = "Package",           Operation = "Create",           Description = "Allows users to Create Packages.",           PortalAdminsOnly = false },
            new Privilege { Id = "package_delete",              Type = "Package",           Operation = "Delete",           Description = "Allows users to Delete Packages.",           PortalAdminsOnly = false },
            new Privilege { Id = "package_read",                Type = "Package",           Operation = "Read",             Description = "Allows users to Read Packages.",             PortalAdminsOnly = false },
            new Privilege { Id = "package_update",              Type = "Package",           Operation = "Update",           Description = "Allows users to Update Packages.",           PortalAdminsOnly = false },
            new Privilege { Id = "packageitem_create",          Type = "PackageItem",       Operation = "Create",           Description = "Allows users to Create PackageItems.",       PortalAdminsOnly = false },
            new Privilege { Id = "packageitem_delete",          Type = "PackageItem",       Operation = "Delete",           Description = "Allows users to Delete PackageItems.",       PortalAdminsOnly = false },
            new Privilege { Id = "packageitem_read",            Type = "PackageItem",       Operation = "Read",             Description = "Allows users to Read PackageItems.",         PortalAdminsOnly = false },
            new Privilege { Id = "packageitem_update",          Type = "PackageItem",       Operation = "Update",           Description = "Allows users to Update PackageItems.",       PortalAdminsOnly = false },
            new Privilege { Id = "page_create",                 Type = "Page",              Operation = "Create",           Description = "Allows users to Create Pages.",              PortalAdminsOnly = false },
            new Privilege { Id = "page_delete",                 Type = "Page",              Operation = "Delete",           Description = "Allows users to Delete Pages.",              PortalAdminsOnly = false },
            new Privilege { Id = "page_read",                   Type = "Page",              Operation = "Read",             Description = "Allows users to Read Pages.",                PortalAdminsOnly = false },
            new Privilege { Id = "page_update",                 Type = "Page",              Operation = "Update",           Description = "Allows users to Update Pages.",              PortalAdminsOnly = false },
            new Privilege { Id = "page_updatecontents",         Type = "Page",              Operation = "UpdateContents",   Description = "Allows users to call UpdateContents on Pages.", PortalAdminsOnly = false },
            new Privilege { Id = "page_updateinfo",             Type = "Page",              Operation = "UpdateInfo",       Description = "Allows users to call UpdateInfo on Pages.",  PortalAdminsOnly = false },
            new Privilege { Id = "page_updateroles",            Type = "Page",              Operation = "UpdateRoles",      Description = "Allows users to call UpdateRoles on Pages.", PortalAdminsOnly = false },
            new Privilege { Id = "pageinfo_create",             Type = "PageInfo",          Operation = "Create",           Description = "Allows users to Create PageInfos.",          PortalAdminsOnly = false },
            new Privilege { Id = "pageinfo_delete",             Type = "PageInfo",          Operation = "Delete",           Description = "Allows users to Delete PageInfos.",          PortalAdminsOnly = false },
            new Privilege { Id = "pageinfo_read",               Type = "PageInfo",          Operation = "Read",             Description = "Allows users to Read PageInfos.",            PortalAdminsOnly = false },
            new Privilege { Id = "pageinfo_update",             Type = "PageInfo",          Operation = "Update",           Description = "Allows users to Update PageInfos.",          PortalAdminsOnly = false },
            new Privilege { Id = "pagerole_create",             Type = "PageRole",          Operation = "Create",           Description = "Allows users to Create PageRoles.",          PortalAdminsOnly = false },
            new Privilege { Id = "pagerole_delete",             Type = "PageRole",          Operation = "Delete",           Description = "Allows users to Delete PageRoles.",          PortalAdminsOnly = false },
            new Privilege { Id = "pagerole_read",               Type = "PageRole",          Operation = "Read",             Description = "Allows users to Read PageRoles.",            PortalAdminsOnly = false },
            new Privilege { Id = "pagerole_update",             Type = "PageRole",          Operation = "Update",           Description = "Allows users to Update PageRoles.",          PortalAdminsOnly = false },
            new Privilege { Id = "privilege_create",            Type = "Privilege",         Operation = "Create",           Description = "Allows users to Create Privileges.",         PortalAdminsOnly = false },
            new Privilege { Id = "privilege_delete",            Type = "Privilege",         Operation = "Delete",           Description = "Allows users to Delete Privileges.",         PortalAdminsOnly = false },
            new Privilege { Id = "privilege_read",              Type = "Privilege",         Operation = "Read",             Description = "Allows users to Read Privileges.",           PortalAdminsOnly = false },
            new Privilege { Id = "privilege_update",            Type = "Privilege",         Operation = "Update",           Description = "Allows users to Update Privileges.",         PortalAdminsOnly = false },
            new Privilege { Id = "queuedemail_create",          Type = "QueuedEmail",       Operation = "Create",           Description = "Allows users to Create QueuedEmails.",       PortalAdminsOnly = false },
            new Privilege { Id = "queuedemail_delete",          Type = "QueuedEmail",       Operation = "Delete",           Description = "Allows users to Delete QueuedEmails.",       PortalAdminsOnly = false },
            new Privilege { Id = "queuedemail_read",            Type = "QueuedEmail",       Operation = "Read",             Description = "Allows users to Read QueuedEmails.",         PortalAdminsOnly = false },
            new Privilege { Id = "queuedemail_update",          Type = "QueuedEmail",       Operation = "Update",           Description = "Allows users to Update QueuedEmails.",       PortalAdminsOnly = false },
            new Privilege { Id = "resource_create",             Type = "Resource",          Operation = "Create",           Description = "Allows users to Create Resources.",          PortalAdminsOnly = false },
            new Privilege { Id = "resource_delete",             Type = "Resource",          Operation = "Delete",           Description = "Allows users to Delete Resources.",          PortalAdminsOnly = false },
            new Privilege { Id = "resource_read",               Type = "Resource",          Operation = "Read",             Description = "Allows users to Read Resources.",            PortalAdminsOnly = false },
            new Privilege { Id = "resource_update",             Type = "Resource",          Operation = "Update",           Description = "Allows users to Update Resources.",          PortalAdminsOnly = false },
            new Privilege { Id = "role_create",                 Type = "Role",              Operation = "Create",           Description = "Allows users to Create Roles.",              PortalAdminsOnly = false },
            new Privilege { Id = "role_delete",                 Type = "Role",              Operation = "Delete",           Description = "Allows users to Delete Roles.",              PortalAdminsOnly = false },
            new Privilege { Id = "role_read",                   Type = "Role",              Operation = "Read",             Description = "Allows users to Read Roles.",                PortalAdminsOnly = false },
            new Privilege { Id = "role_update",                 Type = "Role",              Operation = "Update",           Description = "Allows users to Update Roles.",              PortalAdminsOnly = false },
            new Privilege { Id = "scheduledtask_create",        Type = "ScheduledTask",     Operation = "Create",           Description = "Allows users to Create ScheduledTasks.",     PortalAdminsOnly = false },
            new Privilege { Id = "scheduledtask_delete",        Type = "ScheduledTask",     Operation = "Delete",           Description = "Allows users to Delete ScheduledTasks.",     PortalAdminsOnly = false },
            new Privilege { Id = "scheduledtask_execute",       Type = "ScheduledTask",     Operation = "Execute",          Description = "Allows users to call Execute on ScheduledTasks.", PortalAdminsOnly = false },
            new Privilege { Id = "scheduledtask_read",          Type = "ScheduledTask",     Operation = "Read",             Description = "Allows users to Read ScheduledTasks.",       PortalAdminsOnly = false },
            new Privilege { Id = "scheduledtask_update",        Type = "ScheduledTask",     Operation = "Update",           Description = "Allows users to Update ScheduledTasks.",     PortalAdminsOnly = false },
            new Privilege { Id = "script_create",               Type = "Script",            Operation = "Create",           Description = "Allows users to Create Scripts.",            PortalAdminsOnly = false },
            new Privilege { Id = "script_delete",               Type = "Script",            Operation = "Delete",           Description = "Allows users to Delete Scripts.",            PortalAdminsOnly = false },
            new Privilege { Id = "script_execute",              Type = "FlowDefinition",    Operation = "ExecuteScript",    Description = "Allows users to execute an arbitrary block of C# on the workflow engine", PortalAdminsOnly = false },
            new Privilege { Id = "script_read",                 Type = "Script",            Operation = "Read",             Description = "Allows users to Read Scripts.",              PortalAdminsOnly = false },
            new Privilege { Id = "script_update",               Type = "Script",            Operation = "Update",           Description = "Allows users to Update Scripts.",            PortalAdminsOnly = false },
            new Privilege { Id = "sentemail_create",            Type = "SentEmail",         Operation = "Create",           Description = "Allows users to Create SentEmails.",         PortalAdminsOnly = false },
            new Privilege { Id = "sentemail_delete",            Type = "SentEmail",         Operation = "Delete",           Description = "Allows users to Delete SentEmails.",         PortalAdminsOnly = false },
            new Privilege { Id = "sentemail_read",              Type = "SentEmail",         Operation = "Read",             Description = "Allows users to Read SentEmails.",           PortalAdminsOnly = false },
            new Privilege { Id = "sentemail_update",            Type = "SentEmail",         Operation = "Update",           Description = "Allows users to Update SentEmails.",         PortalAdminsOnly = false },
            new Privilege { Id = "submission_create",           Type = "Submission",        Operation = "Create",           Description = "Allows users to Create Submissions.",        PortalAdminsOnly = false },
            new Privilege { Id = "submission_delete",           Type = "Submission",        Operation = "Delete",           Description = "Allows users to Delete Submissions.",        PortalAdminsOnly = false },
            new Privilege { Id = "submission_read",             Type = "Submission",        Operation = "Read",             Description = "Allows users to Read Submissions.",          PortalAdminsOnly = false },
            new Privilege { Id = "submission_update",           Type = "Submission",        Operation = "Update",           Description = "Allows users to Update Submissions.",        PortalAdminsOnly = false },
            new Privilege { Id = "template_buildemailto",       Type = "Template",          Operation = "BuildEmailTo",     Description = "Allows users to call BuildEmailTo on Templates.", PortalAdminsOnly = false },
            new Privilege { Id = "template_create",             Type = "Template",          Operation = "Create",           Description = "Allows users to Create Templates.",          PortalAdminsOnly = false },
            new Privilege { Id = "template_delete",             Type = "Template",          Operation = "Delete",           Description = "Allows users to Delete Templates.",          PortalAdminsOnly = false },
            new Privilege { Id = "template_read",               Type = "Template",          Operation = "Read",             Description = "Allows users to Read Templates.",            PortalAdminsOnly = false },
            new Privilege { Id = "template_render",             Type = "Template",          Operation = "Render",           Description = "Allows users to call Render on Templates.",  PortalAdminsOnly = false },
            new Privilege { Id = "template_update",             Type = "Template",          Operation = "Update",           Description = "Allows users to Update Templates.",          PortalAdminsOnly = false },
            new Privilege { Id = "user_create",                 Type = "User",              Operation = "Create",           Description = "Allows users to Create Users.",              PortalAdminsOnly = false },
            new Privilege { Id = "user_delete",                 Type = "User",              Operation = "Delete",           Description = "Allows users to Delete Users.",              PortalAdminsOnly = false },
            new Privilege { Id = "user_read",                   Type = "User",              Operation = "Read",             Description = "Allows users to Read Users.",                PortalAdminsOnly = false },
            new Privilege { Id = "user_update",                 Type = "User",              Operation = "Update",           Description = "Allows users to Update Users.",              PortalAdminsOnly = false },
            new Privilege { Id = "userrole_create",             Type = "UserRole",          Operation = "Create",           Description = "Allows users to Create UserRoles.",          PortalAdminsOnly = false },
            new Privilege { Id = "userrole_delete",             Type = "UserRole",          Operation = "Delete",           Description = "Allows users to Delete UserRoles.",          PortalAdminsOnly = false },
            new Privilege { Id = "userrole_read",               Type = "UserRole",          Operation = "Read",             Description = "Allows users to Read UserRoles.",            PortalAdminsOnly = false },
            new Privilege { Id = "userrole_update",             Type = "UserRole",          Operation = "Update",           Description = "Allows users to Update UserRoles.",          PortalAdminsOnly = false },
            new Privilege { Id = "workflowevent_create",        Type = "WorkflowEvent",     Operation = "Create",           Description = "Allows users to Create WorkflowEvents.",     PortalAdminsOnly = false },
            new Privilege { Id = "workflowevent_delete",        Type = "WorkflowEvent",     Operation = "Delete",           Description = "Allows users to Delete WorkflowEvents.",     PortalAdminsOnly = false },
            new Privilege { Id = "workflowevent_read",          Type = "WorkflowEvent",     Operation = "Read",             Description = "Allows users to Read WorkflowEvents.",       PortalAdminsOnly = false },
            new Privilege { Id = "workflowevent_update",        Type = "WorkflowEvent",     Operation = "Update",           Description = "Allows users to Update WorkflowEvents.",     PortalAdminsOnly = false }
        };
    }
}
