using cCoder.Data.Models.Packaging;

namespace cCoder.Core.Exposures.Setup;

public static partial class UIBaseline
{
    private static Package FolderRoles => new()
    {
        Name = "FolderRoles",
        Description = "Generated by App export.",
        Category = "Dynamic",
        SourceApi = "https://ccoder.co.uk/Api/",
        Items =
        [
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "icons",
  "Name": "Administrators"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "icons",
  "Name": "Users"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "icons",
  "Name": "Guests"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content",
  "Name": "Administrators"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content",
  "Name": "Users"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content",
  "Name": "Guests"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/flags",
  "Name": "Administrators"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/flags",
  "Name": "Users"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/flags",
  "Name": "Guests"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "data",
  "Name": "Administrators"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "data",
  "Name": "Users"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "data",
  "Name": "Guests"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation",
  "Name": "Administrators"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation",
  "Name": "Users"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation",
  "Name": "Guests"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/standarduserguide",
  "Name": "Administrators"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/standarduserguide",
  "Name": "Users"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/standarduserguide",
  "Name": "Guests"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/csvtransactionprocessing",
  "Name": "Administrators"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/csvtransactionprocessing",
  "Name": "Users"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/csvtransactionprocessing",
  "Name": "Guests"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/statemanagement",
  "Name": "Administrators"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/statemanagement",
  "Name": "Users"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/statemanagement",
  "Name": "Guests"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "data/transactions",
  "Name": "Administrators"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "data/transactions",
  "Name": "Users"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "data/transactions",
  "Name": "Guests"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "data/transactions/received",
  "Name": "Administrators"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "data/transactions/received",
  "Name": "Users"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "data/transactions/received",
  "Name": "Guests"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation",
  "Name": "Administrators"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation",
  "Name": "Users"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation",
  "Name": "Guests"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/dms",
  "Name": "Administrators"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/dms",
  "Name": "Users"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/dms",
  "Name": "Guests"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/app management",
  "Name": "Administrators"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/app management",
  "Name": "Users"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/app management",
  "Name": "Guests"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/app management/cultures",
  "Name": "Administrators"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/app management/cultures",
  "Name": "Users"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/app management/cultures",
  "Name": "Guests"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/app management/components",
  "Name": "Administrators"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/app management/components",
  "Name": "Users"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/app management/components",
  "Name": "Guests"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/app management/configuration",
  "Name": "Administrators"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/app management/configuration",
  "Name": "Users"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/app management/configuration",
  "Name": "Guests"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/app management/layouts",
  "Name": "Administrators"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/app management/layouts",
  "Name": "Users"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/app management/layouts",
  "Name": "Guests"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/app management/templates",
  "Name": "Administrators"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/app management/templates",
  "Name": "Users"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/app management/templates",
  "Name": "Guests"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/app management/theming",
  "Name": "Administrators"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/app management/theming",
  "Name": "Users"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/app management/theming",
  "Name": "Guests"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/app management/mail management",
  "Name": "Administrators"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/app management/mail management",
  "Name": "Users"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/app management/mail management",
  "Name": "Guests"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/app management/scheduling",
  "Name": "Administrators"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/app management/scheduling",
  "Name": "Users"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/app management/scheduling",
  "Name": "Guests"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/app management/log stream",
  "Name": "Administrators"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/app management/log stream",
  "Name": "Users"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/app management/log stream",
  "Name": "Guests"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/app management/security",
  "Name": "Administrators"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/app management/security",
  "Name": "Users"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/app management/security",
  "Name": "Guests"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/app management/resources",
  "Name": "Administrators"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/app management/resources",
  "Name": "Users"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/app management/resources",
  "Name": "Guests"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/cms",
  "Name": "Administrators"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/cms",
  "Name": "Users"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/cms",
  "Name": "Guests"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/calendar management",
  "Name": "Administrators"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/calendar management",
  "Name": "Users"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/core documentation/calendar management",
  "Name": "Guests"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/sso documentation",
  "Name": "Administrators"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/sso documentation",
  "Name": "Users"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/sso documentation",
  "Name": "Guests"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/sso documentation/forgot your password",
  "Name": "Administrators"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/sso documentation/forgot your password",
  "Name": "Users"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/sso documentation/forgot your password",
  "Name": "Guests"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/sso documentation/managing your profile",
  "Name": "Administrators"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/sso documentation/managing your profile",
  "Name": "Users"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/sso documentation/managing your profile",
  "Name": "Guests"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/sso documentation/logging in",
  "Name": "Administrators"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/sso documentation/logging in",
  "Name": "Users"
}
"""
            },
            new PackageItem
            {
                Type = "Core/FolderRole",
                Data = """
{
  "Path": "content/documentation/sso documentation/logging in",
  "Name": "Guests"
}
"""
            },
        ]
    };
}
