using cCoder.Data.Models.Packaging;

namespace cCoder.Core.Exposures.Setup;

public static partial class UIBaseline
{
    private static Package CalendarEvents => new()
    {
        Name = "CalendarEvents",
        Description = "Generated by App export.",
        Category = "Dynamic",
        SourceApi = "https://ccoder.co.uk/Api/",
        Items =
        [
        ]
    };
}
