using cCoder.Data.Models.Packaging;

namespace cCoder.Core.Exposures.Setup;

public static partial class UIBaseline
{
    private static Package Calendars => new()
    {
        Name = "Calendars",
        Description = "Generated by App export.",
        Category = "Dynamic",
        SourceApi = "https://ccoder.co.uk/Api/",
        Items =
        [
            new PackageItem
            {
                Type = "Core/Calendar",
                Data = """
{
  "Name": "TestAdminCalendar",
  "Description": "Test Admin Calendar"
}
"""
            },
            new PackageItem
            {
                Type = "Core/Calendar",
                Data = """
{
  "Name": "TestAdminCalendar",
  "Description": "Test Admin Calendar"
}
"""
            },
            new PackageItem
            {
                Type = "Core/Calendar",
                Data = """
{
  "Name": "TestAdminCalendar",
  "Description": "Test Admin Calendar"
}
"""
            },
            new PackageItem
            {
                Type = "Core/Calendar",
                Data = """
{
  "Name": "TestAdminCalendar",
  "Description": "Test Admin Calendar"
}
"""
            },
            new PackageItem
            {
                Type = "Core/Calendar",
                Data = """
{
  "Name": "TestAdminCalendar",
  "Description": "Test Admin Calendar"
}
"""
            },
            new PackageItem
            {
                Type = "Core/Calendar",
                Data = """
{
  "Name": "TestAdminCalendar",
  "Description": "Test Admin Calendar"
}
"""
            },
            new PackageItem
            {
                Type = "Core/Calendar",
                Data = """
{
  "Name": "TestAdminCalendar",
  "Description": "Test Admin Calendar"
}
"""
            },
            new PackageItem
            {
                Type = "Core/Calendar",
                Data = """
{
  "Name": "TestAdminCalendar",
  "Description": "Test Admin Calendar"
}
"""
            },
            new PackageItem
            {
                Type = "Core/Calendar",
                Data = """
{
  "Name": "TestAdminCalendar",
  "Description": "Test Admin Calendar"
}
"""
            },
            new PackageItem
            {
                Type = "Core/Calendar",
                Data = """
{
  "Name": "TestAdminCalendar",
  "Description": "Test Admin Calendar"
}
"""
            },
            new PackageItem
            {
                Type = "Core/Calendar",
                Data = """
{
  "Name": "TestAdminCalendar",
  "Description": "Test Admin Calendar"
}
"""
            },
            new PackageItem
            {
                Type = "Core/Calendar",
                Data = """
{
  "Name": "TestAdminCalendar",
  "Description": "Test Admin Calendar"
}
"""
            },
            new PackageItem
            {
                Type = "Core/Calendar",
                Data = """
{
  "Name": "TestAdminCalendar",
  "Description": "Test Admin Calendar"
}
"""
            },
            new PackageItem
            {
                Type = "Core/Calendar",
                Data = """
{
  "Name": "TestAdminCalendar",
  "Description": "Test Admin Calendar"
}
"""
            },
            new PackageItem
            {
                Type = "Core/Calendar",
                Data = """
{
  "Name": "TestAdminCalendar",
  "Description": "Test Admin Calendar"
}
"""
            },
            new PackageItem
            {
                Type = "Core/Calendar",
                Data = """
{
  "Name": "TestAdminCalendar",
  "Description": "Test Admin Calendar"
}
"""
            },
            new PackageItem
            {
                Type = "Core/Calendar",
                Data = """
{
  "Name": "TestAdminCalendar",
  "Description": "Test Admin Calendar"
}
"""
            },
            new PackageItem
            {
                Type = "Core/Calendar",
                Data = """
{
  "Name": "TestAdminCalendar",
  "Description": "Test Admin Calendar"
}
"""
            },
            new PackageItem
            {
                Type = "Core/Calendar",
                Data = """
{
  "Name": "TestAdminCalendar",
  "Description": "Test Admin Calendar"
}
"""
            },
            new PackageItem
            {
                Type = "Core/Calendar",
                Data = """
{
  "Name": "TestAdminCalendar",
  "Description": "Test Admin Calendar"
}
"""
            },
            new PackageItem
            {
                Type = "Core/Calendar",
                Data = """
{
  "Name": "TestAdminCalendar",
  "Description": "Test Admin Calendar"
}
"""
            },
            new PackageItem
            {
                Type = "Core/Calendar",
                Data = """
{
  "Name": "TestAdminCalendar",
  "Description": "Test Admin Calendar"
}
"""
            },
            new PackageItem
            {
                Type = "Core/Calendar",
                Data = """
{
  "Name": "TestAdminCalendar",
  "Description": "Test Admin Calendar"
}
"""
            },
            new PackageItem
            {
                Type = "Core/Calendar",
                Data = """
{
  "Name": "TestAdminCalendar",
  "Description": "Test Admin Calendar"
}
"""
            },
            new PackageItem
            {
                Type = "Core/Calendar",
                Data = """
{
  "Name": "TestAdminCalendarAdmin",
  "Description": "Test Admin Calendar"
}
"""
            },
            new PackageItem
            {
                Type = "Core/Calendar",
                Data = """
{
  "Name": "AsAdmin_CalendarEventCRUD_ReturnsNoErrors",
  "Description": "Test Admin Calendar"
}
"""
            },
            new PackageItem
            {
                Type = "Core/Calendar",
                Data = """
{
  "Name": "AsAdmin_CalendarEventCRUD_ReturnsNoErrors",
  "Description": "Test Admin Calendar"
}
"""
            },
            new PackageItem
            {
                Type = "Core/Calendar",
                Data = """
{
  "Name": "AsAdmin_CalendarEventCRUD_ReturnsNoErrors",
  "Description": "Test Admin Calendar"
}
"""
            },
            new PackageItem
            {
                Type = "Core/Calendar",
                Data = """
{
  "Name": "AsAdmin_CalendarEventCRUD_ReturnsNoErrors",
  "Description": "Test Admin Calendar"
}
"""
            },
            new PackageItem
            {
                Type = "Core/Calendar",
                Data = """
{
  "Name": "AsAdmin_CalendarEventCRUD_ReturnsNoErrors",
  "Description": "Test Admin Calendar"
}
"""
            },
            new PackageItem
            {
                Type = "Core/Calendar",
                Data = """
{
  "Name": "AsAdmin_CalendarEventCRUD_ReturnsNoErrors",
  "Description": "Test Admin Calendar"
}
"""
            },
            new PackageItem
            {
                Type = "Core/Calendar",
                Data = """
{
  "Name": "AsAdmin_CalendarEventCRUD_ReturnsNoErrors",
  "Description": "Test Admin Calendar"
}
"""
            },
        ]
    };
}
