<Project>
  <PropertyGroup>
    <SuppressNETCoreSdkPreviewMessage>true</SuppressNETCoreSdkPreviewMessage>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup Condition="'$(MSBuildProjectExtension)' == '.csproj'">
    <PackageReference Include="cCoder.CodeAnalysis" Version="2026.9.23.1632" IncludeAssets="analyzers;build;buildTransitive" PrivateAssets="all" />
    <PackageReference Include="cCoder.CodeAnalysis.Contracts" Version="2026.9.23.1632" />
  </ItemGroup>
</Project>
