<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="8.10.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="10.0.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\cCoder.Core\cCoder.Core.csproj" />
    <ProjectReference Include="..\Apps\HostedServices\HostedServices.csproj" />
    <PackageReference Include="cCoder.AppSecurity" Version="2026.8.12.1556" />
    <PackageReference Include="cCoder.ContentManagement" Version="2026.8.12.1352" />
    <PackageReference Include="cCoder.Data" Version="2026.8.12.1324" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\Apps\Web\appsettings.json"
          Link="Configuration\Web.appsettings.json"
          CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\Apps\HostedServices\appsettings.json"
          Link="Configuration\HostedServices.appsettings.json"
          CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\Apps\Workflow\local.settings.json"
          Link="Configuration\Workflow.local.settings.json"
          CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
